In [1]:
import numpy as np

In [2]:
a = np.random.randn((10))

In [3]:
b = np.random.randn((10))

In [4]:
a

array([-0.73590273,  0.2091757 ,  0.12334396, -1.4729582 , -0.93543182,
       -1.0979479 ,  0.33697708, -1.10266432,  0.49515501,  0.45119077])

In [5]:
b

array([-0.21797918,  0.21013831, -1.53563437, -0.82225435, -0.3993599 ,
       -0.09063882, -0.03182018, -0.46579724,  0.37511008,  0.93207722])

In [6]:
a + b

array([-0.95388191,  0.41931402, -1.41229041, -2.29521255, -1.33479172,
       -1.18858672,  0.30515691, -1.56846156,  0.87026509,  1.383268  ])

In [7]:
a - b

array([-5.17923546e-01, -9.62611815e-04,  1.65897833e+00, -6.50703847e-01,
       -5.36071915e-01, -1.00730908e+00,  3.68797260e-01, -6.36867077e-01,
        1.20044932e-01, -4.80886450e-01])

In [8]:
a * b

array([ 0.16041147,  0.04395583, -0.18941122,  1.21114629,  0.37357396,
        0.0995167 , -0.01072267,  0.513618  ,  0.18573764,  0.42054464])

In [9]:
a * 2

array([-1.47180546,  0.4183514 ,  0.24668792, -2.9459164 , -1.87086363,
       -2.1958958 ,  0.67395417, -2.20532864,  0.99031002,  0.90238155])

In [10]:
1/a

array([-1.35887525,  4.78066999,  8.10740971, -0.67890589, -1.069025  ,
       -0.91079003,  2.96756085, -0.90689431,  2.01956958,  2.21635737])

In [11]:
a > 0

array([False,  True,  True, False, False, False,  True, False,  True,
        True])

In [12]:
# Array as an index
a[a>0]

array([0.2091757 , 0.12334396, 0.33697708, 0.49515501, 0.45119077])

In [13]:
x = np.array([[1,2,3],[4,5,6]])

In [14]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
x[x<10]

array([1, 2, 3, 4, 5, 6])