In [1]:
import numpy as np

In [2]:
a = np.random.randn((10))

In [3]:
b = np.random.randn((10))

In [4]:
a

array([ 0.80841661, -1.94143201, -1.92703799,  0.56731532,  0.24425703,
       -1.31443278,  0.834828  , -1.6832365 ,  1.07980472,  2.13465356])

In [5]:
b

array([-0.15584154,  0.86273921,  1.62369829,  0.01881585, -0.17044261,
       -1.13145532, -0.19174104,  1.76175791, -1.69646465, -1.41674923])

In [6]:
a + b

array([ 0.65257507, -1.0786928 , -0.3033397 ,  0.58613117,  0.07381442,
       -2.4458881 ,  0.64308697,  0.07852141, -0.61665993,  0.71790433])

In [7]:
a - b

array([ 0.96425815, -2.80417121, -3.55073628,  0.54849947,  0.41469964,
       -0.18297746,  1.02656904, -3.44499442,  2.77626938,  3.55140279])

In [8]:
a * b

array([-0.12598489, -1.67494951, -3.12892829,  0.01067452, -0.0416318 ,
        1.48722196, -0.16007079, -2.96545523, -1.83185055, -3.02426878])

In [9]:
a * 2

array([ 1.61683322, -3.88286402, -3.85407598,  1.13463064,  0.48851406,
       -2.62886556,  1.669656  , -3.36647301,  2.15960945,  4.26930711])

In [10]:
1/a

array([ 1.23698596, -0.51508371, -0.51893113,  1.76268817,  4.09404801,
       -0.76078444,  1.19785153, -0.59409358,  0.92609337,  0.46846009])

In [11]:
a > 0

array([ True, False, False,  True,  True, False,  True, False,  True,
        True])

In [12]:
# Array as an index
a[a>0]

array([0.80841661, 0.56731532, 0.24425703, 0.834828  , 1.07980472,
       2.13465356])

In [13]:
x = np.array([[1,2,3],[4,5,6]])

In [14]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
x[x<10]

array([1, 2, 3, 4, 5, 6])

In [17]:
np.ones_like([1,2,3])

array([1, 1, 1])

In [18]:
np.full([1,2,3],5)

array([[[5, 5, 5],
        [5, 5, 5]]])

In [19]:
arr1 =np.array([1,2,3], dtype=np.float64)

In [20]:
arr2 =np.array([1,2,3], dtype=np.int32)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
arr = np.array([1,2,3,4,5], dtype = np.int64)

In [24]:
arr.dtype

dtype('int64')

In [25]:
float_arr = arr.astype(np.float64)

In [26]:
float_arr.dtype

dtype('float64')

In [30]:
arrt = np.array([1,2,3])

In [33]:
arrt.astype(float)

array([1., 2., 3.])

In [34]:
arrt.dtype

dtype('int32')

In [35]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [36]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_array = np.arange(10)

In [38]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [40]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [43]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
empty_unit32 = np.empty(8,dtype='u4')

In [46]:
empty_unit32

array([4232644624,        500,    3801156,    7536732,    7602277,
          7340149,    7340078,        121], dtype=uint32)