In [1]:
import numpy as np

In [2]:
a = np.random.randn((10))

In [3]:
b = np.random.randn((10))

In [4]:
a

array([ 0.53016331, -0.76680899, -0.7848825 , -0.37710202, -0.28428943,
        1.13685902, -2.15796836, -0.0825332 ,  1.01298207, -2.69444131])

In [5]:
b

array([ 0.49271198, -0.57742485, -0.64947622,  1.56353329,  1.12399815,
        0.48144463,  1.27237979,  0.78966524,  1.63692604,  0.38911311])

In [6]:
a + b

array([ 1.02287529, -1.34423384, -1.43435872,  1.18643127,  0.83970872,
        1.61830366, -0.88558857,  0.70713203,  2.64990811, -2.3053282 ])

In [7]:
a - b

array([ 0.03745132, -0.18938414, -0.13540628, -1.94063531, -1.40828758,
        0.65541439, -3.43034815, -0.87219844, -0.62394398, -3.08355443])

In [8]:
a * b

array([ 0.26121782,  0.44277456,  0.50976252, -0.58961156, -0.31954079,
        0.54733467, -2.74575533, -0.0651736 ,  1.65817672, -1.04844245])

In [9]:
a * 2

array([ 1.06032662, -1.53361798, -1.569765  , -0.75420404, -0.56857886,
        2.27371805, -4.31593671, -0.1650664 ,  2.02596413, -5.38888262])

In [10]:
1/a

array([  1.88621125,  -1.30410574,  -1.27407606,  -2.65180229,
        -3.51754195,   0.87961654,  -0.46339882, -12.11633595,
         0.98718431,  -0.37113445])

In [11]:
a ** 0.5

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.72812314,        nan,        nan,        nan,        nan,
       1.06623591,        nan,        nan, 1.0064701 ,        nan])

In [12]:
a > 0

array([ True, False, False, False, False,  True, False, False,  True,
       False])

In [13]:
# Array as an index
a[a>0]

array([0.53016331, 1.13685902, 1.01298207])

In [14]:
x = np.array([[1,2,3],[4,5,6]])

In [15]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [16]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [17]:
x[x<10]

array([1, 2, 3, 4, 5, 6])

In [18]:
np.ones_like([1,2,3])

array([1, 1, 1])

In [19]:
np.full([1,2,3],5)

array([[[5, 5, 5],
        [5, 5, 5]]])

In [20]:
arr1 =np.array([1,2,3], dtype=np.float64)

In [21]:
arr2 =np.array([1,2,3], dtype=np.int32)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
arr = np.array([1,2,3,4,5], dtype = np.int64)

In [25]:
arr.dtype

dtype('int64')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr.dtype

dtype('float64')

In [28]:
arrt = np.array([1,2,3])

In [29]:
arrt.astype(float)

array([1., 2., 3.])

In [30]:
arrt.dtype

dtype('int32')

In [31]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [32]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [33]:
int_array = np.arange(10)

In [34]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [36]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [37]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
empty_unit32 = np.empty(8,dtype='u4')

In [40]:
empty_unit32

array([2501348352,        371, 1702130533, 1763729522, 1852383347,
       1634301033, 1702521196,  537538148], dtype=uint32)