In [1]:
import numpy as np

In [16]:
x = np.array([10,9,8,7,11])

In [18]:
np.square(x) # Square 

array([100,  81,  64,  49, 121], dtype=int32)

In [19]:
np.sqrt(x) # Square root

array([3.16227766, 3.        , 2.82842712, 2.64575131, 3.31662479])

In [20]:
np.max(x) # maximum value in whole array

11

In [25]:
np.power(x,2) # Power 

array([1000,  729,  512,  343, 1331], dtype=int32)

In [21]:
y = np.array([7,5,18,2,4])

In [22]:
y

array([ 7,  5, 18,  2,  4])

In [23]:
np.maximum(x,y) # compare both arrays and return the largest one

array([10,  9, 18,  7, 11])