In [1]:
import numpy as np

In [2]:
x = np.array([1,7,9,8,5])

In [3]:
x

array([1, 7, 9, 8, 5])

In [4]:
x[4]

5

In [5]:
x[x>5]

array([7, 9, 8])

In [6]:
# Fancy Indexing 
x[[2,1]]

array([9, 7])

### Slicing 

In [7]:
s = np.random.rand(10,10)

In [8]:
s

array([[0.244561  , 0.7948437 , 0.83647736, 0.02043998, 0.59831419,
        0.94046849, 0.89070125, 0.36100859, 0.81080318, 0.24579392],
       [0.11907684, 0.6242065 , 0.73816892, 0.25343518, 0.25576905,
        0.54613443, 0.90264002, 0.44935747, 0.20432367, 0.31001026],
       [0.51825274, 0.57247679, 0.53540509, 0.93703679, 0.07187285,
        0.0768471 , 0.33070589, 0.33112648, 0.09700876, 0.64410059],
       [0.00585305, 0.05686097, 0.93513189, 0.15823995, 0.64102134,
        0.63705652, 0.09899111, 0.37630918, 0.88400387, 0.94351606],
       [0.77093714, 0.18528887, 0.56133742, 0.41023838, 0.39161917,
        0.53663271, 0.7847717 , 0.49201919, 0.40628296, 0.82562766],
       [0.70065049, 0.3379642 , 0.72978049, 0.50531877, 0.9054793 ,
        0.97851417, 0.73727868, 0.41909264, 0.30328937, 0.74343338],
       [0.65224155, 0.27842335, 0.83674983, 0.3268837 , 0.73108276,
        0.43337632, 0.91299589, 0.20729631, 0.31662704, 0.87905061],
       [0.47086169, 0.10776251, 0.9631211

In [9]:
s[0]

array([0.244561  , 0.7948437 , 0.83647736, 0.02043998, 0.59831419,
       0.94046849, 0.89070125, 0.36100859, 0.81080318, 0.24579392])

In [10]:
s[0][5]

0.9404684908470584

In [11]:
s[1:10:2]

array([[0.11907684, 0.6242065 , 0.73816892, 0.25343518, 0.25576905,
        0.54613443, 0.90264002, 0.44935747, 0.20432367, 0.31001026],
       [0.00585305, 0.05686097, 0.93513189, 0.15823995, 0.64102134,
        0.63705652, 0.09899111, 0.37630918, 0.88400387, 0.94351606],
       [0.70065049, 0.3379642 , 0.72978049, 0.50531877, 0.9054793 ,
        0.97851417, 0.73727868, 0.41909264, 0.30328937, 0.74343338],
       [0.47086169, 0.10776251, 0.96312116, 0.90902134, 0.15392383,
        0.43831781, 0.72832551, 0.04928032, 0.52455513, 0.27787833],
       [0.30170227, 0.17259044, 0.55075884, 0.7372623 , 0.38344482,
        0.5277528 , 0.6948022 , 0.00113432, 0.39096282, 0.79647184]])

In [12]:
s[::,0:4]

array([[0.244561  , 0.7948437 , 0.83647736, 0.02043998],
       [0.11907684, 0.6242065 , 0.73816892, 0.25343518],
       [0.51825274, 0.57247679, 0.53540509, 0.93703679],
       [0.00585305, 0.05686097, 0.93513189, 0.15823995],
       [0.77093714, 0.18528887, 0.56133742, 0.41023838],
       [0.70065049, 0.3379642 , 0.72978049, 0.50531877],
       [0.65224155, 0.27842335, 0.83674983, 0.3268837 ],
       [0.47086169, 0.10776251, 0.96312116, 0.90902134],
       [0.42596167, 0.97219955, 0.45682297, 0.29486041],
       [0.30170227, 0.17259044, 0.55075884, 0.7372623 ]])

In [13]:
pract = np.ones((5,5))

In [14]:
pract

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
pract[1:-1,1:-1] = 0 

In [16]:
pract

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
checker_board_pattern = np.ones((5,5))

In [18]:
checker_board_pattern

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
checker_board_pattern[0:5:2,0:5:2] = 0 

In [20]:
checker_board_pattern

array([[0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0.]])

In [21]:
fb_ground = np.ones((5,5))

In [22]:
fb_ground

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
fb_ground[::,0:5:2]=0

In [24]:
fb_ground

array([[0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

## Book Exercise

In [25]:
arr = np.arange(10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[5]

5

In [28]:
arr[5:9]

array([5, 6, 7, 8])

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12 # Value propogation 

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8]

In [33]:
arr_slice

array([12, 12, 12])

In [34]:
arr_slice[1] = 12345

In [35]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [36]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
arr2d[2]

array([7, 8, 9])

##### Multi Dimensioal Array

In [38]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [39]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d.shape

(2, 2, 3)

In [41]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
old_values = arr3d[0].copy()

In [43]:
arr3d[0] = 42

In [44]:
arr3d[0]

array([[42, 42, 42],
       [42, 42, 42]])

In [45]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[0] = old_values

In [47]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[1,0]

array([7, 8, 9])

##### Indexing with Slice

In [49]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [50]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [51]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

#### Boolean Indexing

In [54]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [55]:
data = np.random.rand(7,4)

In [56]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [57]:
data

array([[0.22492653, 0.66530479, 0.89386455, 0.09122919],
       [0.84233849, 0.64037912, 0.05310588, 0.66313471],
       [0.16398666, 0.07300553, 0.16625252, 0.65121165],
       [0.97916002, 0.49614735, 0.28403257, 0.88784087],
       [0.52425996, 0.50200138, 0.95687534, 0.46118516],
       [0.24763977, 0.86234182, 0.96837003, 0.75937378],
       [0.25305153, 0.56664827, 0.9125117 , 0.92260406]])

In [58]:
names.dtype

dtype('<U4')

In [74]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [75]:
data [data<0] = 0

In [76]:
data[names == 'Bob']

array([[0.22492653, 0.66530479, 0.89386455, 0.09122919],
       [0.97916002, 0.49614735, 0.28403257, 0.88784087]])

In [77]:
data[names == 'Bob', 2:]

array([[0.89386455, 0.09122919],
       [0.28403257, 0.88784087]])

In [78]:
data[names == 'Bob',3]

array([0.09122919, 0.88784087])

In [79]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [80]:
data[~(names == 'Bob')]

array([[0.84233849, 0.64037912, 0.05310588, 0.66313471],
       [0.16398666, 0.07300553, 0.16625252, 0.65121165],
       [0.52425996, 0.50200138, 0.95687534, 0.46118516],
       [0.24763977, 0.86234182, 0.96837003, 0.75937378],
       [0.25305153, 0.56664827, 0.9125117 , 0.92260406]])

In [81]:
cond = names =='Bob'

In [82]:
cond

array([ True, False, False,  True, False, False, False])

In [83]:
data[~cond]

array([[0.84233849, 0.64037912, 0.05310588, 0.66313471],
       [0.16398666, 0.07300553, 0.16625252, 0.65121165],
       [0.52425996, 0.50200138, 0.95687534, 0.46118516],
       [0.24763977, 0.86234182, 0.96837003, 0.75937378],
       [0.25305153, 0.56664827, 0.9125117 , 0.92260406]])

In [84]:
mask  = (names == 'Bob') | (names == 'Will')

In [85]:
mask

array([ True, False,  True,  True,  True, False, False])

In [88]:
data[mask]

array([[0.22492653, 0.66530479, 0.89386455, 0.09122919],
       [0.16398666, 0.07300553, 0.16625252, 0.65121165],
       [0.97916002, 0.49614735, 0.28403257, 0.88784087],
       [0.52425996, 0.50200138, 0.95687534, 0.46118516]])

In [90]:
data[data<0] =0

In [91]:
data[names!='Joe'] =7

In [92]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.84233849, 0.64037912, 0.05310588, 0.66313471],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.24763977, 0.86234182, 0.96837003, 0.75937378],
       [0.25305153, 0.56664827, 0.9125117 , 0.92260406]])

#### Fancy Indexing

In [62]:
arr = np.empty((8,4))

In [64]:
for i in range(8):
    arr[i]=i 

In [65]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [66]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [67]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [68]:
arr[[-3,-5,-6]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.]])

In [69]:
arr = np.arange(32).reshape((8,4))

In [70]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [71]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [72]:
 arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [73]:
 arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])