In [1]:
import numpy as np

In [2]:
x = np.array([1,7,9,8,5])

In [3]:
x

array([1, 7, 9, 8, 5])

In [4]:
x[4]

5

In [5]:
x[x>5]

array([7, 9, 8])

In [6]:
# Fancy Indexing 
x[[2,1]]

array([9, 7])

### Slicing 

In [7]:
s = np.random.rand(10,10)

In [8]:
s

array([[0.1968744 , 0.24562439, 0.48022316, 0.94416808, 0.62586616,
        0.42635519, 0.16042496, 0.91342884, 0.32412713, 0.99901801],
       [0.80952492, 0.63431058, 0.62664061, 0.43110857, 0.52052348,
        0.51554312, 0.85335088, 0.86787827, 0.52504198, 0.01256688],
       [0.97572105, 0.24856718, 0.68950905, 0.45227152, 0.23556124,
        0.24711297, 0.78856946, 0.01347836, 0.24741508, 0.23358919],
       [0.09776491, 0.9288483 , 0.15496467, 0.96206312, 0.15119554,
        0.66394656, 0.6650524 , 0.12639829, 0.30264687, 0.20809227],
       [0.11722983, 0.4510105 , 0.47132849, 0.42786184, 0.4136569 ,
        0.06709102, 0.78898218, 0.83447957, 0.0988752 , 0.92155555],
       [0.97397462, 0.2611038 , 0.24623694, 0.00490194, 0.06891907,
        0.56461834, 0.30260702, 0.97459491, 0.16401444, 0.63021298],
       [0.48506477, 0.64322998, 0.63309939, 0.47719616, 0.72814272,
        0.20606057, 0.29357773, 0.57508499, 0.44313555, 0.22134576],
       [0.60381725, 0.10975863, 0.9910621

In [9]:
s[0]

array([0.1968744 , 0.24562439, 0.48022316, 0.94416808, 0.62586616,
       0.42635519, 0.16042496, 0.91342884, 0.32412713, 0.99901801])

In [10]:
s[0][5]

0.42635518644701575

In [11]:
s[1:10:2]

array([[0.80952492, 0.63431058, 0.62664061, 0.43110857, 0.52052348,
        0.51554312, 0.85335088, 0.86787827, 0.52504198, 0.01256688],
       [0.09776491, 0.9288483 , 0.15496467, 0.96206312, 0.15119554,
        0.66394656, 0.6650524 , 0.12639829, 0.30264687, 0.20809227],
       [0.97397462, 0.2611038 , 0.24623694, 0.00490194, 0.06891907,
        0.56461834, 0.30260702, 0.97459491, 0.16401444, 0.63021298],
       [0.60381725, 0.10975863, 0.99106213, 0.43499734, 0.4069179 ,
        0.91416749, 0.82659177, 0.60601357, 0.76762165, 0.10802362],
       [0.68948115, 0.08067159, 0.80450714, 0.10624648, 0.82351014,
        0.10335876, 0.78739457, 0.93663935, 0.56138951, 0.53524523]])

In [12]:
s[::,0:4]

array([[0.1968744 , 0.24562439, 0.48022316, 0.94416808],
       [0.80952492, 0.63431058, 0.62664061, 0.43110857],
       [0.97572105, 0.24856718, 0.68950905, 0.45227152],
       [0.09776491, 0.9288483 , 0.15496467, 0.96206312],
       [0.11722983, 0.4510105 , 0.47132849, 0.42786184],
       [0.97397462, 0.2611038 , 0.24623694, 0.00490194],
       [0.48506477, 0.64322998, 0.63309939, 0.47719616],
       [0.60381725, 0.10975863, 0.99106213, 0.43499734],
       [0.89734579, 0.11444392, 0.90836243, 0.11015948],
       [0.68948115, 0.08067159, 0.80450714, 0.10624648]])

In [13]:
pract = np.ones((5,5))

In [14]:
pract

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
pract[1:-1,1:-1] = 0 

In [16]:
pract

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
checker_board_pattern = np.ones((5,5))

In [18]:
checker_board_pattern

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
checker_board_pattern[0:5:2,0:5:2] = 0 

In [20]:
checker_board_pattern

array([[0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0.]])

In [21]:
fb_ground = np.ones((5,5))

In [22]:
fb_ground

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
fb_ground[::,0:5:2]=0

In [24]:
fb_ground

array([[0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])