In [1]:
import numpy as np

In [2]:
x = np.random.randn(3,2)

In [3]:
x

array([[-0.99560997, -0.95364934],
       [ 0.12752813, -0.92520633],
       [-0.56025808,  0.06296708]])

In [4]:
y = np.random.randn(2,3)

In [5]:
y

array([[-1.2317457 ,  0.86812173, -0.01802801],
       [-0.16147421, -1.68268631,  2.014936  ]])

In [6]:
x.dot(y)

array([[ 1.38032807,  0.74038205, -1.90359352],
       [-0.00768526,  1.66754196, -1.86653062],
       [ 0.67992792, -0.59232605,  0.13697497]])

In [7]:
x.transpose()

array([[-0.99560997,  0.12752813, -0.56025808],
       [-0.95364934, -0.92520633,  0.06296708]])

In [8]:
x.trace()

-1.9208162991302853