In [1]:
import numpy as np

In [2]:
x = np.random.randn(3,2)

In [3]:
x

array([[-0.00448446,  0.87808509],
       [-0.16737841, -0.71435618],
       [ 1.63832558, -0.02630435]])

In [4]:
y = np.random.randn(2,3)

In [5]:
y

array([[ 0.656269  ,  2.17126111, -0.44519054],
       [ 0.85532358, -0.64475561, -1.26587551]])

In [6]:
x.dot(y)

array([[ 0.74810387, -0.57588722, -1.10954997],
       [-0.72085095,  0.09716292,  0.97880128],
       [ 1.05268356,  3.5741925 , -0.69606903]])

In [7]:
x.transpose()

array([[-0.00448446, -0.16737841,  1.63832558],
       [ 0.87808509, -0.71435618, -0.02630435]])

In [8]:
x.trace()

-0.7188406368745923

## Book Practice

In [9]:
arr = np.arange(15).reshape((3,5))

In [10]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [12]:
arr = np.random.randn(6,3)

In [13]:
arr

array([[ 1.59849094,  0.93778116, -1.70640109],
       [-1.08630111,  1.50939355, -1.0859066 ],
       [-1.30879356,  1.78524712,  1.1419715 ],
       [-1.24519065,  0.54232218,  0.27403989],
       [ 0.79739437, -0.83954423, -1.52348473],
       [-0.81031617, -0.89581047, -1.69544493]])

In [14]:
np.dot(arr.T,arr)

array([[ 8.29111383, -3.09599378, -3.2248537 ],
       [-3.09599378,  8.14623394,  1.74585816],
       [-3.2248537 ,  1.74585816, 10.66573381]])

In [15]:
arr = np.arange(16).reshape((2,2,4))

In [16]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [26]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [27]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [28]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])