In [1]:
import numpy as np

In [2]:
x = np.array([10,9,7,10,7])

In [3]:
x

array([10,  9,  7, 10,  7])

In [4]:
x.mean() # average

8.6

In [5]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [6]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [7]:
y = x > 6

In [8]:
y

array([ True,  True,  True,  True,  True])

In [9]:
y.sum() # Sum of True value in the array

5

In [10]:
y.any() # Check if any Value is True in array

True

In [11]:
y.all() # Check if all values are TRUE than it return True otherwise False

True

In [12]:
y =x>7

In [13]:
y

array([ True,  True, False,  True, False])

In [14]:
y.sum() # Sum of True value in the array

3

In [15]:
y.any() # Check if any Value is True in array

True

In [16]:
y.all() # Check if all values are TRUE than it return True otherwise False

False

In [17]:
x

array([10,  9,  7, 10,  7])

In [18]:
x.sort()

In [19]:
x

array([ 7,  7,  9, 10, 10])

In [20]:
np.unique(x)

array([ 7,  9, 10])