In [1]:
import numpy as np

In [2]:
x = np.random.randn(4,5)

In [3]:
x

array([[ 0.17653814,  1.03848306,  0.80935743,  0.42968909,  0.38395722],
       [ 0.38966827, -0.15498232,  1.35715836,  0.3197278 ,  0.8274973 ],
       [ 1.61644879, -0.82788937,  1.05277032, -1.12492343, -0.18304418],
       [-1.06821723, -0.7689823 ,  0.70882   , -3.03771789, -1.31253843]])

In [7]:
x.reshape((2,2,5))

array([[[ 0.17653814,  1.03848306,  0.80935743,  0.42968909,
          0.38395722],
        [ 0.38966827, -0.15498232,  1.35715836,  0.3197278 ,
          0.8274973 ]],

       [[ 1.61644879, -0.82788937,  1.05277032, -1.12492343,
         -0.18304418],
        [-1.06821723, -0.7689823 ,  0.70882   , -3.03771789,
         -1.31253843]]])

In [8]:
x.reshape((2,2,5), order = 'F')

array([[[ 0.17653814,  1.03848306,  0.80935743,  0.42968909,
          0.38395722],
        [ 1.61644879, -0.82788937,  1.05277032, -1.12492343,
         -0.18304418]],

       [[ 0.38966827, -0.15498232,  1.35715836,  0.3197278 ,
          0.8274973 ],
        [-1.06821723, -0.7689823 ,  0.70882   , -3.03771789,
         -1.31253843]]])

In [9]:
x.reshape((2,2,5), order = 'C')

array([[[ 0.17653814,  1.03848306,  0.80935743,  0.42968909,
          0.38395722],
        [ 0.38966827, -0.15498232,  1.35715836,  0.3197278 ,
          0.8274973 ]],

       [[ 1.61644879, -0.82788937,  1.05277032, -1.12492343,
         -0.18304418],
        [-1.06821723, -0.7689823 ,  0.70882   , -3.03771789,
         -1.31253843]]])

In [11]:
x.reshape((2,2,-1))

array([[[ 0.17653814,  1.03848306,  0.80935743,  0.42968909,
          0.38395722],
        [ 0.38966827, -0.15498232,  1.35715836,  0.3197278 ,
          0.8274973 ]],

       [[ 1.61644879, -0.82788937,  1.05277032, -1.12492343,
         -0.18304418],
        [-1.06821723, -0.7689823 ,  0.70882   , -3.03771789,
         -1.31253843]]])

In [12]:
x

array([[ 0.17653814,  1.03848306,  0.80935743,  0.42968909,  0.38395722],
       [ 0.38966827, -0.15498232,  1.35715836,  0.3197278 ,  0.8274973 ],
       [ 1.61644879, -0.82788937,  1.05277032, -1.12492343, -0.18304418],
       [-1.06821723, -0.7689823 ,  0.70882   , -3.03771789, -1.31253843]])

In [13]:
x.flatten()

array([ 0.17653814,  1.03848306,  0.80935743,  0.42968909,  0.38395722,
        0.38966827, -0.15498232,  1.35715836,  0.3197278 ,  0.8274973 ,
        1.61644879, -0.82788937,  1.05277032, -1.12492343, -0.18304418,
       -1.06821723, -0.7689823 ,  0.70882   , -3.03771789, -1.31253843])

In [14]:
x.ravel()

array([ 0.17653814,  1.03848306,  0.80935743,  0.42968909,  0.38395722,
        0.38966827, -0.15498232,  1.35715836,  0.3197278 ,  0.8274973 ,
        1.61644879, -0.82788937,  1.05277032, -1.12492343, -0.18304418,
       -1.06821723, -0.7689823 ,  0.70882   , -3.03771789, -1.31253843])