<a href="https://colab.research.google.com/github/dayan2222/Numpy-Practice/blob/master/Numpy_Practice_PIAIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Vs Python Notebook

In [0]:
import numpy as np

In [0]:
l = range(1000000) # Returns List

In [0]:
import numpy as np

In [0]:
d = np.arange(1000000)# arange Returns array

In [5]:
%time for i in range(1,10): r = [x*2 for x in l]

CPU times: user 647 ms, sys: 130 ms, total: 777 ms
Wall time: 781 ms


In [6]:
%time for i in range(1,10): r = d*2

CPU times: user 27.9 ms, sys: 4.2 ms, total: 32.1 ms
Wall time: 33.6 ms


# Multidimensioal Array
    

In [0]:
x = np.zeros((4,4))#zeros create array whose all values are zero

In [8]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((5,5))#ones Returns the one array element

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty((7,7))#empty not necessary all elements will zero it have a random number of values

array([[3.1662209e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

we can also used python list to declare in numpy array

In [0]:
 l = [1,4,5,7]

In [12]:
np.array(l)

array([1, 4, 5, 7])

In [0]:
x=np.arange(1,100,10)#arange within the desired along with step size generates the values

In [14]:
x 

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [0]:
x = np.zeros((10,10))

In [16]:
x.shape

(10, 10)

reshape method used to reshape the array but the number of elements should be same

In [0]:
y = x.reshape((2,2,5,5))

In [18]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [19]:
y.dtype # for datatype DT might be string float int or whatsoever

dtype('float64')

In [20]:
y.ndim

4

# Airthemetic Operations 
Add, Sub, Multiply, Divide and Boolean

In [0]:
a = np.random.randn((10))

In [0]:
b = np.random.randn((10))

In [23]:
a 

array([-0.77634458,  1.98762306, -0.46743739,  1.67362798, -0.42199206,
        0.68629152,  0.68426594, -0.49383136,  2.44996932, -0.0033759 ])

In [24]:
b

array([-0.12675198,  0.96743891,  1.87845667, -0.40616207,  0.22644926,
        0.70651687, -0.41918958, -0.88942339, -2.116676  ,  0.4577888 ])

In [25]:
a+b

array([-0.90309656,  2.95506197,  1.41101928,  1.26746591, -0.1955428 ,
        1.39280839,  0.26507636, -1.38325475,  0.33329331,  0.45441289])

In [26]:
a - b

array([-0.64959259,  1.02018414, -2.34589407,  2.07979005, -0.64844133,
       -0.02022535,  1.10345552,  0.39559202,  4.56664532, -0.4611647 ])

In [27]:
2*a

array([-1.55268915,  3.97524611, -0.93487479,  3.34725595, -0.84398413,
        1.37258304,  1.36853188, -0.98766272,  4.89993863, -0.0067518 ])

In [28]:
1 / a

array([  -1.28808783,    0.5031135 ,   -2.13932393,    0.59750435,
         -2.36971281,    1.45710674,    1.46142011,   -2.02498277,
          0.40816838, -296.21712174])

In [29]:
a > 0

array([False,  True, False,  True, False,  True,  True, False,  True,
       False])

In [30]:
a[a>0]

array([1.98762306, 1.67362798, 0.68629152, 0.68426594, 2.44996932])

# Indexing And Slicing

Specify the start position and ending position and also specify the step size.
- -ve numbers will be marked as last.


In [0]:
x = np.array([1,7,5,6,8,3])

In [32]:
x[4] # indexing of list values

8

## Boolean Indexing

In [33]:
x [x>5]

array([7, 6, 8])

In [34]:
x

array([1, 7, 5, 6, 8, 3])

## Fancy Indexing
Pass a ist and then get the desired element on the selected position which is passed as a list

In [35]:
x[[2,1]]

array([5, 7])

## Slicing


In [0]:
x = np.random.randn(10,10)

In [37]:
x

array([[-0.22640482,  0.04491281, -0.95963494,  1.14789632,  1.38851523,
         1.7750981 , -1.26370507,  1.41567615, -1.156041  , -0.37829295],
       [ 0.38526352, -0.58763891,  0.45826068,  1.6578168 ,  0.37789392,
        -0.44545527, -1.26383428,  0.12387825, -0.90015004,  0.55910798],
       [ 0.28093848,  0.2398032 ,  0.42624057,  0.3836606 ,  1.19969506,
         1.11718013, -0.25944088,  1.05586389, -0.79161101, -1.28890708],
       [ 0.67086746,  0.55279863, -0.85902517,  0.90140108,  1.24234514,
         1.43558024,  0.05012575,  1.21954675,  1.01464036, -0.82203985],
       [-0.52664481,  0.78859381,  1.01061534,  1.56751537, -0.91248854,
        -0.10993654,  1.43620603,  0.63660676, -0.65397567,  1.59971092],
       [-1.24098015,  0.64642567, -0.70438542, -0.01148276, -0.89181083,
        -0.58087969, -0.02709361, -1.2565756 , -0.63713519,  2.08897683],
       [-0.22041874, -1.57397698,  0.79759481, -0.3703391 ,  0.52624822,
        -0.64930743,  1.13055229,  0.63006064

In [38]:
x[0] # will return the first row 

array([-0.22640482,  0.04491281, -0.95963494,  1.14789632,  1.38851523,
        1.7750981 , -1.26370507,  1.41567615, -1.156041  , -0.37829295])

In [39]:
x[0][4] # will return the first row and first column

1.3885152270593584

In [40]:
x [1:10:2] # here is the step size. Hence it leaves the one column from each row

array([[ 0.38526352, -0.58763891,  0.45826068,  1.6578168 ,  0.37789392,
        -0.44545527, -1.26383428,  0.12387825, -0.90015004,  0.55910798],
       [ 0.67086746,  0.55279863, -0.85902517,  0.90140108,  1.24234514,
         1.43558024,  0.05012575,  1.21954675,  1.01464036, -0.82203985],
       [-1.24098015,  0.64642567, -0.70438542, -0.01148276, -0.89181083,
        -0.58087969, -0.02709361, -1.2565756 , -0.63713519,  2.08897683],
       [-0.5236321 , -0.49973193,  0.21294631,  0.85893255,  1.03468357,
        -0.11457703,  0.30588752, -1.00659659,  1.14964987,  0.26666202],
       [-0.76092908, -1.58832679,  2.09056149, -0.3690862 ,  1.88295052,
        -0.97714446, -1.60302361,  0.32085137,  0.36466482, -1.22436246]])

In [41]:
x[::,0:4] # all the rows and four columns from the start

array([[-0.22640482,  0.04491281, -0.95963494,  1.14789632],
       [ 0.38526352, -0.58763891,  0.45826068,  1.6578168 ],
       [ 0.28093848,  0.2398032 ,  0.42624057,  0.3836606 ],
       [ 0.67086746,  0.55279863, -0.85902517,  0.90140108],
       [-0.52664481,  0.78859381,  1.01061534,  1.56751537],
       [-1.24098015,  0.64642567, -0.70438542, -0.01148276],
       [-0.22041874, -1.57397698,  0.79759481, -0.3703391 ],
       [-0.5236321 , -0.49973193,  0.21294631,  0.85893255],
       [-0.95487369, -0.02550143,  0.06009341,  0.75908519],
       [-0.76092908, -1.58832679,  2.09056149, -0.3690862 ]])

In [0]:
x = np.ones((5,5))

In [43]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
x[1:-1,1:-1] = 0

In [45]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])