<a href="https://colab.research.google.com/github/dayan2222/Numpy-Practice/blob/master/PIAIC_Practice_Exercise_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise
a) Import the "numpy" library as "np".

In [0]:
import numpy as np

b) Create an array of shape (2, 3, 4) of zeros.

In [0]:
x = np.zeros((2, 3, 4))

In [3]:
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [4]:
x.shape

(2, 3, 4)

c) Create an array of shape (2, 3, 4) of ones.

In [0]:
x = np.ones((2, 3, 4))

In [6]:
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
x.shape

(2, 3, 4)

d) Create an array with values 0 to 999 using the "np.arange" function

In [0]:
x = np.arange(0,999)

In [9]:
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

e) Create an array from the list [2, 3.2, 5.5, -6.4, -2.2, 2.4] and assign it to the variable "a"

In [0]:
l = [2, 3.2, 5.5, -6.4, -2.2, 2.4]

In [0]:
a = np.array(l)

In [12]:
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

f) Do you know what a[1] will equal? Print it to see

In [13]:
a[1]

3.2

g) Try printing a[1:4] to see what that equals

In [14]:
a[1:4]

array([ 3.2,  5.5, -6.4])